### ISSUE TITLE
Working with # IRI

### ISSUE THREAD

**Issue by fils** [deiu/rdf2go#1]
So I am seeing if I can read a VoID doc in turtle.  All is going very well till I try to look for triples based on a # IRI.  

When I try and do this line (full code ref below)
```
vds.DownloadURL = getObject(g, triples[triple].Subject, rdf2go.NewResource("http://www.w3.org/ns/dcat#downloadURL"))
```

It doesn't work since of course everything after # is effectively ignored which is of course correct in many cases.  Still, in SPARQL I can set up a query and use a prefix that has a #'s base.  

Is there a way to conduct a search in rdf2go with IRIs that have the # structure like in https://github.com/OpenCoreData/ocdGarden/blob/master/GraphUtils/VOIDReader/void.ttl

Code Ref:  https://github.com/OpenCoreData/ocdGarden/blob/master/GraphUtils/VOIDReader/main.go

**Comment by deiu** [comment]
Hi,

That looks like a bug to me. IRIs should be allowed to contain frag IDs. I'll take a look asap.

**Comment by deiu** [comment]
I've pushed a patch to one of the [dependencies](https://github.com/deiu/gon3/commit/f84eb1e0bd629a62676207d0a47516da8338cf60) that should solve this issue. Please let me know if you run into any other issues. You need to do a `go get -u github.com/deiu/rdf2go` to pull in changes in the dependencies. Going to leave this issue open until you confirm that everything is fine.

**Comment by fils** [comment]
@deiu everything is processing fine now it looks like..  thanks!

Feel free to close.   

ps.  Solid is on my list of "things to dive into"  so I was shocked (in a happy way) to see you connected in a big way to that.   I work with the NSF EarthCube project on some issues and I am really trying to advocate decentralized approaches rather than monolithic aggregations patterns.  I think Sold is very interesting!    (ok..  I digressed)  ;)

**Comment by deiu** [comment]
You're welcome!
