### ISSUE TITLE
rdf2go usage with SMW?

### ISSUE THREAD

**Issue by HQ1791** [deiu/rdf2go#12]
Hello,

I have read this [Paper](https://ceur-ws.org/Vol-632/paper18.pdf) and it mentioned the usage of rdf2go with Semantic Mediawiki (SMW). I came to your repository, hoping for some example or some demo that can show how one can make it work with SMW.

I am looking forward to getting any help from you regarding the rdf2go integration with SMW!

Thanks.

**Comment by deiu** [comment]
Hi @HQ1791. Having a quick look at the paper it seems that it uses a different library -- i.e. RDF2Go (Java). I'm sorry I can't help you with that. :)
