### ISSUE TITLE
IterTriples causes concurrent map error

### ISSUE THREAD

**Issue by philharveyonline** [deiu/rdf2go#16]
I'm a happy user of this library but we get occasional errors from the Go runtime's 'concurrent map misuse detector' which makes the program crash: https://go.dev/doc/go1.6#runtime

I believe IterTriples() needs to be changed to avoid this error, e.g. by adding a lock:
https://github.com/deiu/rdf2go/blob/c39eb296d51cdc8bfb5e5b3f2e1f94d940e61e34/graph.go#L107

You may also need to use this same lock inside the reader methods.

Alternatively you could avoid creating a goroutine inside IterTriples().

**Comment by deiu** [comment]
Hi @philharveyonline! Thanks for raising this issue. I'm afraid I don't have the bandwidth to make the fixes but would welcome a PR with open arms.

**Comment by philharveyonline** [comment]
Thanks, I created pull request #17 to fix this. Please could you review/merge it?
