### ISSUE TITLE
How can a prefix be used?

### ISSUE THREAD

**Issue by BoraBak** [deiu/rdf2go#5]
For example:
`rdf ` is the prefix for `<http://www.w3.org/1999/02/22-rdf-syntax-ns#> .`
Therefore, in the .ttl file we should write:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
...
ont:TACTIC rdf:type owl:Class ;
    neo4voc:name "TACTIC" .

ont:CustomId rdf:type owl:DatatypeProperty ;
    neo4voc:name "CustomId" .
```

**Comment by deiu** [comment]
Yes, that is the Turtle way to specify and use prefixes. However, that is just one serialization format. This library abstracts the serialization and instead allows devs to work with triples at a lower level.

**Comment by BoraBak** [comment]
@deiu Any future plans to support it?

**Comment by deiu** [comment]
There are no plans to support it, since that means supporting writing Turtle by hand, which is not the purpose of this library.
