### ISSUE TITLE
Convert TTL or JSON-LD to GO struct

### ISSUE THREAD

**Issue by BoraBak** [deiu/rdf2go#6]
I'm able to convert TTL file to a JSON-LD format. Note, the conversion is not perfect because it lacks of `@Context` metadata. I compared the output using this repo vs online converters.
But how can I convert from JSON-LD to an a Golang structs? Or even better, can I convert straight from RDF TTL to Golang struct?

**Comment by nvkp** [comment]
@BoraBak  check out this Golang package that uses tags and reflection to parse TTL directly to a Golang struct: https://github.com/nvkp/turtle

**Comment by deiu** [comment]
Closing this issue.
